max_width = 100
hard_tabs = true
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_modules = true
reorder_impl_items = true
remove_nested_parens = true
edition = "2024"
style_edition = "2024"
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
unstable_features = true
format_macro_matchers = true
format_macro_bodies = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
hex_literal_case = "Upper"
