//! Public key management for code-signing verification.
//!
//! The default key (key_id = 0) is injected at build time via a build-options
//! module read from keys/codesign_public.key by innigkeit/custom.zig.
//!
//! Key rotation: a future implementation can read an override from the EFI
//! variable "InnigkeitSigningKey" (GUID to be defined) via efi_var_get.

const codesign_key_options = @import("codesign_key_options");

/// Raw 32-byte Ed25519 public key for key_id = 0.
/// Generated by `zig build codesign -- keygen` and stored in keys/codesign_public.key.
pub const default_public_key: [32]u8 = codesign_key_options.default_public_key;

/// Look up the public key for the given key_id.
/// Currently only key_id == 0 (the compiled-in default) is supported.
pub fn getPublicKey(key_id: u32) ?[32]u8 {
    return switch (key_id) {
        0 => default_public_key,
        else => null, // future: EFI variable override
    };
}
