name: CI/CD
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "**.zig"
      - "**.zig.zon"
      - "**.c"
      - "**.h"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "**.zig"
      - "**.zig.zon"
      - "**.c"
      - "**.h"
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: "git: checkout"
        uses: actions/checkout@v6

      - name: "zig: setup"
        uses: mlugg/setup-zig@v2

      - name: "apt: install QEMU/AAVMF/swtpm"
        run: sudo apt-get update && sudo apt-get install -y qemu-system-x86 qemu-system-arm qemu-efi-aarch64 ovmf swtpm swtpm-tools

      - name: "rust: bare-metal target"
        run: rustup target add x86_64-unknown-none

      - name: "zig: generate codesign keypair"
        run: zig build codesign -- keygen

      - name: "zig: lint"
        run: zig fmt --check --ast-check .

      - name: "zig: build_all"
        run: zig build build_all --summary all

      - name: "zig: verify"
        run: zig build verify -Darm=true -Dtpm=true --summary all
